### PR TITLE
Change package name

### PR DESCRIPTION
**Pull request by mnapoli**
Shorter name without "compiler".

### CODE REVIEW

**Comment by mnapoli** [comment]
The name of the project should be changed too IMO.

**Comment by moufmouf** [comment]
Yep. I added the "compiler" part to explain that these tests are about testing container/compilers using _definition-interop_ rather than objects implementing the _definition-interop_. But indeed, this package name is too long and it is unlikely we will ever provide a set of tests for objects implementing the _definition-interop_ interface.

So ok for renaming all this. I will do it as soon as I have 5 minutes (kind of busy right now!)

**Comment by mnapoli** [comment]
> I added the "compiler" part to explain that these tests are about testing container/compilers using definition-interop

I don't understand why "compilers"? I could see a link with "containers", but there is nothing related to compilers here right?

**Comment by moufmouf** [comment]
Well, when I wrote compilers, that was in the sense of a "container builder" (if you speak in Symfony terms).

My initial thought was that _definition-interop_ would mainly be used by containers that compile themselves (rather than "runtime" containers), hence the "compiler" word.

I plan to write a blog post some day about this comparison. In essence, if you use _definition-interop_ without a compiler (or without a container using APCu caching), the container setup time will increase linearly (O(n)) with the number of entries (we need to create one definition object for each service that can be created). This kind of completely negates the performance benefits of using a DI container (a container is supposed to only create instances of the services that are used).

So my initial thoughts were that the only sane way to use _definition-interop_ was to use a compiler that generates a container. Using a compiled container, the setup time of the container does not increase at all with the number of services (O(1))

Later, I realized that putting definitions in cache using APCu was also a possible solution to reach a O(1) performance.

Anyway, I'll remove the "compiler" part of the name, this was just an explanation on why initially added "compiler" in the name.

**Comment by mnapoli** [comment]
OK I understand. But I just want to stress that compiled containers today are a large minority, and applications run fine. Pimple for example works exactly like this (O(n) and no cache) but it's perfectly fine for many use cases.

**Comment by moufmouf** [comment]
Yep, true.
Ok, wreaking havoc right now on this package. Accepting this pull-request and renaming.

**Pull request merged**
